import test from 'node:test'; import assert from 'node:assert/strict';
import { BODY_STAGES, TERRITORY_SIZE, TERRITORY_STEAL_COST } from '../src/game/constants.js';
import { createPet, socialAction, buyCosmetic, COSMETIC_SHOP, rankingsView } from '../src/game/engine.js';
import { createAppleBoard, appleHasMove, refreshAppleBoardIfStuck } from '../src/game/apple-game.js';
import { interactionHungerCostForBody, lifeHungerCostsForBody } from '../src/game/activity.js';

test('v648 확정 체형 28단계와 배고픔 완화',()=>{ assert.equal(BODY_STAGES.length,28); assert.deepEqual(BODY_STAGES.map(x=>x.label), ['마름레고','보통레고','육덕레고','짭덥레고','멸떱레고','통통레고','비떱레고','뚱뚱레고','세자리레고','빅빅우먼레고','로얄비떱레고','하마레고','코끼리레고','맘모스레고','매태지레고','돼룩돼룩레고','초대룩레고','돼황레고','괴수돼지레고','침대파괴돼지레고','재난문자돼지레고','국가비상돼지레고','프로토케라톱스레고','트리케라톱스레고','스테고사우루스레고','브라키오사우루스레고','파타고티탄레고','아르헨티노사우루스레고']); assert.equal(interactionHungerCostForBody(4520),6); assert.deepEqual(lifeHungerCostsForBody(4520),{work:14,rest:7,exercise:20}); });
test('파손 시스템 제거와 영토 5x5/탈취비',()=>{ assert.equal(TERRITORY_SIZE,5); assert.equal(TERRITORY_STEAL_COST,20); });
test('사과 막힘 감지 후 새 판 생성',()=>{ const c={appleBoard:Array.from({length:10},()=>Array(10).fill(null)),applePendingPoints:0,appleScore:0,appleRemovedCount:0,appleSuccesses:0,appleProcessedRequestIds:[]}; assert.equal(appleHasMove(c),false); assert.equal(refreshAppleBoardIfStuck(c,()=>0),true); assert.equal(c.appleBoardsGenerated,2); assert.equal(c.appleBoard[0][0],1); });
test('꾸미기 상점은 포인트를 실제 소모',()=>{ const p=createPet('u','레고'); p.stats.points=2000; const r=buyCosmetic(p,'nameSparkle',new Date('2026-08-09T00:00:00Z')); assert.equal(r.ok,true); assert.equal(p.stats.points,800); assert.ok(COSMETIC_SHOP.length>=15); assert.equal(COSMETIC_SHOP.some(x=>x.kind==='title'),false); assert.ok(COSMETIC_SHOP.some(x=>x.id==='nameRainbow')); assert.ok(COSMETIC_SHOP.some(x=>x.id==='statusRainbow')); });
test('교미 궁합은 1~100',()=>{ const state={pets:{},requests:{},relationships:{},publicEvents:[],users:{}}; const a=createPet('a','A'),b=createPet('b','B'); state.pets[a.id]=a;state.pets[b.id]=b; const req=socialAction(state,a,b,'requestMating',{},new Date()); const request=Object.values(state.requests)[0]; const old=Math.random; Math.random=()=>0; try { const r=socialAction(state,b,a,'acceptMating',{requestId:request.id},new Date()); assert.equal(r.compatibility,1); } finally {Math.random=old;} });


test('번개반응 시즌 랭킹은 낮은 초수가 우선',()=>{ const state={pets:{},users:{},relationships:{},pokes:{}}; const a=createPet('a','A'),b=createPet('b','B'); a.records.seasonBestReactionMs=180;a.records.seasonBestReactionAt='2026-08-09T00:00:00Z';b.records.seasonBestReactionMs=220;b.records.seasonBestReactionAt='2026-08-09T00:00:01Z';state.pets[a.id]=a;state.pets[b.id]=b; const r=rankingsView(state,a.id); assert.match(r.reaction[0].displayName,/A$/); assert.equal(r.reaction[0].ms,180); });
test('교미 문구는 10퍼센트 구간별 최신 문구를 사용',()=>{ const state={pets:{},requests:{},relationships:{},publicEvents:[],users:{}}; const a=createPet('a','A'),b=createPet('b','B');state.pets[a.id]=a;state.pets[b.id]=b;socialAction(state,a,b,'requestMating',{},new Date());const req=Object.values(state.requests)[0];const old=Math.random;Math.random=()=>0.99;try{const r=socialAction(state,b,a,'acceptMating',{requestId:req.id},new Date());assert.equal(r.compatibility,100);assert.match(r.resultText,/상어|한국밥|호야|호야계단남녀|축하드립니다/);}finally{Math.random=old;}});
